[package]
name = "md"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["derive", "cargo", "unicode"] }
human-panic.workspace = true
matte = { path = "../matte" }
shell-words.workspace = true
terminal_size.workspace = true
thiserror.workspace = true
